### ISSUE TITLE
Add a slash command to list topics subscribed to a Mattermost channel

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-aws-SNS#11]

**Comment by msvbhat** [comment]
I want to take this one.

**Comment by msvbhat** [comment]
Hi, I wanted some of your opinions and suggestions about how to retrieve topics subscribed to MM channel.

I was thinking of storing the topics in a custom struct after the subscription confirmation. But then the information remains in memory and is lost when plugin subprocess is restarted.

Can you people suggest a better ways to fetch the topics? Should I store it in some datastore and fetch later during ExecuteCommand? Or does AWS SNS provides a way of fetching this detail?

**Comment by levb** [comment]
@msvbhat I am not familiar with the API on the AWS side, but if there is a way to retrieve the list of subscriptions, and then filter it down to what's required by the request - it'd do nicely IMO.

Otherwise, maybe look at https://github.com/mattermost/mattermost-plugin-github/blob/master/server/subscriptions.go as an example?

**Comment by msvbhat** [comment]
Thanks for the help.
I couldn't find any good API from AWS side which would give us relevant information. There are few APIs which would be useful, but they take some inputs (token, subscriptionID etc) which would again require us to store them in k/v store.

So I think storing the values in k/v store upon successful "Subscription Confirmation" and getting them from k/v store when command is invoked is easier way to handle it for now. But if you know there is a better way, please let me know.

I wrote skeleton code for registering and executing the command yesterday. I will try and add the functionality today.
