### ISSUE TITLE
Dead Link Found In README For SNS Confirmation

### ISSUE THREAD

**Issue by greglloyd-t3** [mattermost/mattermost-plugin-aws-SNS#43]
In the current release of the README the "[Follow this documentation](https://docs.safe.com/fme/html/FME_Server_Documentation/ReferenceManual/Amazon_SNS_Publisher_Configure_AWS_Subscription.html)" link in the second step of "Step 2: Configure plugin in Amazon AWS" leads to a 404.  

Can this be updated to the correct location of this information?

**Comment by jfrerich** [comment]
Thank you for bringing this to our attention, @greglloyd-t3!  The linked PR will fix the issue!

**Comment by greglloyd-t3** [comment]
Thanks for the help!
