### ISSUE TITLE
Add autocomplete icon

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-aws-SNS#46]
Since v5.24 slash commands can provide an `svg` via  `AutocompleteIconData` in `model.Command` that is then shown in the autocomplete list. This ticket is about adding the icon in `assets` to the slash command.

Include screenhots from a dark and a bright theme in the PR description, as there might be the need for a separate icon with a white background for autocomplete.

Similar PRs:
For GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/359
For Jira plugin https://github.com/mattermost/mattermost-plugin-jira/pull/653

**Comment by Amyth07** [comment]
Hey can I take this, if no one have claimed it yet?

**Comment by hanzei** [comment]
All yours @Amyth07 :+1: Let me know if you have any questions.

**Comment by hanzei** [comment]
@Amyth07 Just wanted to check if you are still working on this. Let me know if you have any questions.

**Comment by ByeongsuPark** [comment]
Hi, Would I be able to take this issue?

**Comment by hanzei** [comment]
Sure, thanks @ByeongsuPark :+1:
