### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-aws-SNS#53]
Needed to release a new version that has platform specific bundles.

Needed changes:

- [x] https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/50
- [x] https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/52
- [x] https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/54
- [x] https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/56

**Comment by justinegeffen** [comment]
@hanzei, when will this be ready for release? I'd like to create the Gitbook for it.

**Comment by hanzei** [comment]
The release is current awaiting the review of @DHaussermann, but I don't expect it to happen before Christmas.
