### ISSUE TITLE
teamChannel setting doesn't follow the pattern

### ISSUE THREAD

**Issue by zzbmmbzz** [mattermost/mattermost-plugin-aws-SNS#58]
Hi,
I have tried install SNS plugin but after config as the document, plugin could not enable, it show the error as bellow:
```
{"level":"error","ts":1608709092.99835,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"com.mattermost.aws-sns","error":"teamChannel setting doesn't follow the pattern $TEAM_NAME,$CHANNEL_NAME"}
```

`my configuration`
![image](https://user-images.githubusercontent.com/41033532/102972118-21eda780-452d-11eb-98eb-9d18c4110b0f.png)

Mattermost Version: 5.30.1
Amazon AWS SNS Plugin: v1.1.0

**Comment by hanzei** [comment]
Hi @zzbmmbzz,

The format is `teamname,channelname`. What is the team name you are using?

**Comment by zzbmmbzz** [comment]
> Hi @zzbmmbzz,
> 
> The format is `teamname,channelname`. What is the team name you are using?

Hi hanzei,
teamname,channelname: `https://chat.mydomain.com/skytech/channels/test-channel`
I get this url on channel Info
Thanks,
Edgar

**Comment by hanzei** [comment]
Could you please input `skytech,test-channel` into that settings field and try if that resolves the error?

**Comment by zzbmmbzz** [comment]
> Could you please input `skytech,test-channel` into that settings field and try if that resolves the error?

let me try

**Comment by zzbmmbzz** [comment]
> Could you please input `skytech,test-channel` into that settings field and try if that resolves the error?

HI @hanzei ,

It's working

Thank you so much,
Edgar
