### ISSUE TITLE
Issue with formatting

### ISSUE THREAD

**Issue by camaer** [mattermost/mattermost-plugin-aws-SNS#66]
Using the latest plugin version I'm getting some weird formatting issue. See the attached screenshot.

Mattermost Server: 5.37.0
Mattermost Desktop Client: Mac 4.7.1
AWS SNS Plugin: 1.2.0

![Screen Shot 2021-08-05 at 12 09 36 PM](https://user-images.githubusercontent.com/35572989/128384993-16454b61-127c-46db-8780-f3624e250468.png)

Any idea what might cause this ?

**Comment by larkox** [comment]
This seems to be an issue with the main product. I just created a PR: https://github.com/mattermost/mattermost-webapp/pull/8534
