### ISSUE TITLE
Migrate the plugin to use bot accounts

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-aws-SNS#9]
After migration, we can remove the `Username` System Console setting, simplifying plugin configuration.

**Comment by vesari** [comment]
I'd like to work on this if I may?

**Comment by jasonblais** [comment]
Go for it, thank you @vesari! If any questions, don't hesitate to let us know

cc @levb @jfrerich

**Comment by jfrerich** [comment]
Thanks for taking this on, @vesari!  If you have any questions feel free to ask, or in out [~contributors](https://community.mattermost.com/core/channels/tickets)
 channel

**Comment by vesari** [comment]
Can you please explain what it entails to migrate the plugin to use bot accounts? By "bot", do you mean AWS Chatbot? Thanks! @jasonblais @levb @jfrerich

**Comment by jasonblais** [comment]
@vesari Good question - glad you asked! The intent is to migrate this plugin to use Mattermost Bot Accounts https://docs.mattermost.com/deployment/bots.html

Here are two example PRs that did this for GitHub and GitLab plugins
 - https://github.com/mattermost/mattermost-plugin-gitlab/pull/42
 - https://github.com/mattermost/mattermost-plugin-github/pull/83
